# Generated by Django 4.0.3 on 2023-05-09 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Metakinhsh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metak_from', models.CharField(max_length=100, verbose_name='Από')),
                ('metak_to', models.CharField(max_length=100, verbose_name='Προορισμός')),
                ('date_from', models.DateField(verbose_name='Ημ/νία Από')),
                ('date_to', models.DateField(verbose_name='Ημ/νία Έως')),
                ('km', models.IntegerField(verbose_name='Χιλιόμετρα')),
                ('egkrish', models.BooleanField(verbose_name='Έγκριση')),
                ('pragmat', models.BooleanField(verbose_name='Πραγματοποιήθηκε')),
                ('aitiologia', models.TextField(verbose_name='Αιτιολογία')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
