# Generated by Django 4.2.3 on 2023-07-11 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metak', '0003_alter_metakinhsh_options_alter_metakinhsh_egkrish_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metakinhsh',
            name='handler',
            field=models.CharField(choices=[('Επόπτης', 'Επόπτης'), ('Οικονομικό', 'Οικονομικό')], default=None, max_length=80, verbose_name='Χειριστής'),
        ),
    ]
