# Generated by Django 4.2.3 on 2023-07-11 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metak', '0007_alter_metakinhsh_date_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metakinhsh',
            name='handler',
            field=models.CharField(blank=True, choices=[('Επόπτης', 'Επόπτης'), ('Οικονομικό', 'Οικονομικό')], default=None, max_length=80, null=True, verbose_name='Χειριστής'),
        ),
    ]
